// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMEwTCvaruoBTQb5JgSUJoLsQDDQBhtx4',
    appId: '1:108856268297:web:d2ef9794bdcb4346a7cad8',
    messagingSenderId: '108856268297',
    projectId: 'education-50fe8',
    authDomain: 'education-50fe8.firebaseapp.com',
    storageBucket: 'education-50fe8.firebasestorage.app',
    measurementId: 'G-WKY8WLRHZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxDeaetDnywVkxRIFyFS7l9Lwn26zISCY',
    appId: '1:108856268297:android:f7936b8ab365c25aa7cad8',
    messagingSenderId: '108856268297',
    projectId: 'education-50fe8',
    storageBucket: 'education-50fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd39ekr3Iz_yH-Bo2vlb_0HPT_iJ1lNqo',
    appId: '1:108856268297:ios:e0483d1f023f2c34a7cad8',
    messagingSenderId: '108856268297',
    projectId: 'education-50fe8',
    storageBucket: 'education-50fe8.firebasestorage.app',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd39ekr3Iz_yH-Bo2vlb_0HPT_iJ1lNqo',
    appId: '1:108856268297:ios:e0483d1f023f2c34a7cad8',
    messagingSenderId: '108856268297',
    projectId: 'education-50fe8',
    storageBucket: 'education-50fe8.firebasestorage.app',
    iosBundleId: 'com.example.education',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMEwTCvaruoBTQb5JgSUJoLsQDDQBhtx4',
    appId: '1:108856268297:web:0e0567408d84ad35a7cad8',
    messagingSenderId: '108856268297',
    projectId: 'education-50fe8',
    authDomain: 'education-50fe8.firebaseapp.com',
    storageBucket: 'education-50fe8.firebasestorage.app',
    measurementId: 'G-G5NRDNLHLM',
  );
}
